import type { Config } from "tailwindcss";

/**
 * Design tokens ported 1:1 from the LUMINA Optics prototype (source of truth).
 * Do not change visual values here without a matching change in the prototype.
 */
const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#4d4635",
        primary: "#f2ca50",
        "surface-container-high": "#262a31",
        "on-tertiary": "#082b72",
        outline: "#99907c",
        "primary-fixed-dim": "#e9c349",
        "on-secondary": "#452b00",
        surface: "#10141a",
        error: "#ffb4ab",
        "on-tertiary-container": "#254188",
        "primary-container": "#d4af37",
        background: "#10141a",
        "on-background": "#dfe2eb",
        "on-surface": "#dfe2eb",
        "on-primary-fixed": "#241a00",
        "inverse-primary": "#735c00",
        "on-surface-variant": "#d0c5af",
        "secondary-container": "#dc9100",
        "surface-bright": "#353940",
        "tertiary-fixed": "#dbe1ff",
        "secondary-fixed-dim": "#ffb955",
        "surface-tint": "#e9c349",
        secondary: "#ffb955",
        "tertiary-container": "#97b0ff",
        "surface-variant": "#31353c",
        "on-secondary-container": "#4f3100",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#31353c",
        "tertiary-fixed-dim": "#b4c5ff",
        "on-error": "#690005",
        "inverse-surface": "#dfe2eb",
        "surface-dim": "#10141a",
        "on-tertiary-fixed": "#00174b",
        "surface-container": "#1c2026",
        "on-primary-container": "#554300",
        "on-secondary-fixed-variant": "#633f00",
        "secondary-fixed": "#ffddb4",
        "surface-container-lowest": "#0a0e14",
        "on-primary": "#3c2f00",
        "primary-fixed": "#ffe088",
        "error-container": "#93000a",
        tertiary: "#bfcdff",
        "surface-container-low": "#181c22",
        "inverse-on-surface": "#2d3137",
        "on-primary-fixed-variant": "#574500",
        "on-tertiary-fixed-variant": "#27438a",
        "on-secondary-fixed": "#291800",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "container-max": "88rem",
        "space-4xl": "6rem",
        "space-2xs": "0.25rem",
        "gutter-desktop": "2rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-xs": "0.5rem",
        "space-3xl": "4.5rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1rem",
      },
      fontFamily: {
        "body-md": ["var(--font-hanken)", "sans-serif"],
        "headline-lg": ["var(--font-syne)", "sans-serif"],
        "editorial-caption": ["var(--font-hanken)", "sans-serif"],
        "display-hero-mobile": ["var(--font-syne)", "sans-serif"],
        "telemetry-xs": ["var(--font-jetbrains)", "monospace"],
        "headline-lg-mobile": ["var(--font-syne)", "sans-serif"],
        "body-sm": ["var(--font-hanken)", "sans-serif"],
        "headline-sm": ["var(--font-syne)", "sans-serif"],
        "telemetry-data": ["var(--font-jetbrains)", "monospace"],
        "headline-md": ["var(--font-syne)", "sans-serif"],
        "body-lg": ["var(--font-hanken)", "sans-serif"],
        "display-hero": ["var(--font-syne)", "sans-serif"],
      },
      fontSize: {
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "editorial-caption": ["11px", { lineHeight: "16px", letterSpacing: "0.14em", fontWeight: "500" }],
        "display-hero-mobile": ["38px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "telemetry-xs": ["10px", { lineHeight: "14px", letterSpacing: "0.12em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "500" }],
        "telemetry-data": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "500" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "display-hero": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-right": {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.35s ease-out both",
        "slide-in-right": "slide-in-right 0.3s ease-out both",
      },
    },
  },
  plugins: [],
};

export default config;
